[functions."stripe-webhook"]
  included_files = ["netlify/functions/stripe-webhook.js"]
  node_bundler = "esbuild"
  # Très important :
  # Empêche Netlify de modifier le body (Stripe a besoin du corps brut)
  [functions."stripe-webhook".event_source]
    rawBody = true
