# -------------------------------
# Netlify configuration pour Windows
# -------------------------------

[build]
  # Pas de commande de build nécessaire pour ce projet statique
  # 'publish' pointe vers le dossier contenant index.html
  command = "echo 'skip build'"
  publish = "main"

[functions]
  # Dossier contenant tes fonctions Netlify (*.js)
  directory = "netlify/functions"

# -------------------------------
# Headers pour le contenu HTML
# -------------------------------
[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "/"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"

# -------------------------------
# Redirections pour les fonctions et SPA
# -------------------------------
[[redirects]]
  # Redirection pour les fonctions Netlify
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  # Redirection globale vers index.html pour SPA
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
