[build]
  publish = "."
  command = "echo 'Static site'"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = ""
  port = 8888
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false