[build]
  command = "echo 'skip build'"
  publish = "main"


[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "/"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"

[[redirects]]
  # Redirection pour les fonctions Netlify
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  # Redirection globale vers index.html, forcée pour ne pas bloquer les fonctions
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
